### PR TITLE
Fix luacheck warning

### LINKED ISSUE #178: Check Lua source code with luacheck
```
Checking test-run/lib/tarantool-python/test-run/lib/tarantool-python/tests/suites/box.lua 1 warning

    test-run/lib/tarantool-python/test-run/lib/tarantool-python/tests/suites/box.lua:2:1: (W121) setting read-only global variable os

```

Tarantool issue: https://github.com/tarantool/tarantool/issues/4681

### PR DESCRIPTION
**Pull request by ligurio**
Closes #178

### CODE REVIEW

File: unit/suites/box.lua [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #!/usr/bin/env tarantool
-os = require('os')
+local os = require('os')
```
Comment (Totktonada) [inline unit/suites/box.lua:2]: The same warning is reported for `test/cluster-py/master.lua`.

Comment (Totktonada) [reply unit/suites/box.lua:2]: Fixed. Verified this way: `luacheck . --exclude-files test-run --read-globals box`.

**Review by Totktonada — APPROVED** [review]
I'll wait for CI and push.
